pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'docker'
        }
    }
    environment {
        CI = 'true'
    }
    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }
    stages {
        stage('Build For Testing') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy to Gh-Pages') {
            when {
                branch 'production'
            }
            steps {
                sh '''
                    git config --global user.email "jingley22@gmail.com"
                    git config --global user.name "Jon Ross Ingley"
                '''
                withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'GIT_PASSWD', usernameVariable: 'GIT_USER')]) {
                    sh 'git remote set-url origin https://jingley22@gmail.com:${GIT_PASSWD}@github.com/jingley/jrs-website'
                }
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}
