pipeline {
    agent {
        docker {
            image 'node:12-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true' 
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') { 
            steps {
		        script {
                	npm install --save-dev cross-env 
                	npm test
		        }
            }
        }
        stage('Deliver') {
            steps{
		        script {
                	npm run build
                	npm start & sleep 1
                	echo $! > .pidfile
                	echo Visit http://localhost:3000 to see your Node.js/React application in action.
                	input message: 'Finished using the web site? (Click "Proceed" to continue)
                	kill $(cat .pidfile)
        	    }
	        } 
        }
    }
}
