pipeline {
    agent {
        dockerfile {
            filename 'docker/Dockerfile'
            additionalBuildArgs '--build-arg ssh'
        }
    }
    environment {
        CI = 'true'
    }
    options {
        buildDiscarder logRotator( 
                    daysToKeepStr: '16', 
                    numToKeepStr: '10'
            )
    }
    stages {
        stage('Build For Testing') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy to Gh-Pages') {
            when {
                branch 'production'
            }
            steps {
                sh '''
                    git config --global user.email "jingley22@gmail.com"
                    git config --global user.name "Jon Ross Ingley"
                    git config --global credential.helper cache
                    ssh -T git@github.com:jingley/jrs-website.git
                '''
                sh './jenkins/scripts/deploy.sh'
            }
        }
    }
}
